### ISSUE TITLE
End of year party / Civic Hackathon

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/rft-operations#1]
Agenda:
- Friday Night: Pitch ideas and form teams.
- Saturday: BBQ, games, mountains, trees, hack, and win prizes.

Needs:
- [ ] Clear description of event to share
- [ ] Research and/or pre-download available open data from local sources
- [ ] Pitch night (Friday) materials (sticky  notes, markers, etc...)
- [ ] Pitch night (Friday) venue
- [ ] Pitch night (Friday) food - StartUp Colorado provided (tentative)
- [ ] Event (Saturday) venue - Current plan is Justin's house but we'll probably max out at around 20 people there.
- [ ] Event (Saturday) food - StartUp Colorado provided (tentative)
- [x] Event (Saturday) prizes - Ski passes from SkiCo

Useful stuff:
- Public Data - https://github.com/toddmotto/public-apis

**Comment by stevetarver** [comment]
Consider:
* How many attendees don't know GitHub? We could have a short course to get them an account.
* If we had a readme for creating issues, managing the project, people could create ideas as issues, etc. and help manage the project. BUT, perhaps project mgmt is better left to a single person so we have consistent use, etc.
* At what attendee count does dividing into separate teams improve efficiency and joy?
* If we have multiple teams, how do we storm and form? We could group by skill to be more effective, but I like working with people I don't know and skills I haven't mastered. What is optimal to ensure people have a great time.
* Pre-planning: should we consolidate existing ideas and request for help and add them to the global list after ideation (so we don't anchor the conversation - see what everyone comes up with, include existing ideas, then vote on best)
* Have a durable way to record ideas. This could be gh issues, but we want to avoid anything that slows down ideation - and we need a concise list available to all. If there is good internet - the issues landing page may work.
* How do we record our achievements. On one hand, we want everyone to have a great time, but we also want to document what we accomplish to build RFT. We should take good photos and create a blog about it. A previous employer blogged about their hack house event and I was so inspired, I joined the company...

**TODO**: Groom these ideas and record them as actionable items that we can delegate to pre-planning people, etc.

**Comment by stevetarver** [comment]
oops - wrong button

**Comment by justinlewis** [comment]
Converted your bullets to numbers 

1. Tough to say. Friday will tell us a lot!
2. I think we should select 3 or 4 ideas and each should have their own repo where they manage things how they want. 
3. I would like people to form their teams around the ideas that are pitched. That way the people pitching ideas has to recruit team members while those member also opt-in. That way they have more ownership over the team/idea. 
4. I think this should be a decision of the people forming the teams. I agree that we should set the precedence that this is an opportunity to take on a new role and learn. 
5. Not a bad idea to have some ideas ready to kick things along or fill gaps.
6. I was thinking we all get together at a place in Carbondale where we just use short pitches followed by sticky note based votes for the ideas. Kind of like how startup weekends work. The point would be to just facilitate ideas to team forming in a supportive way. 
7. Yes yes and yes. My over arching goal is that we release a couple really simple Alpha level apps/visualizations into the world. These will likely tell stories about our communities. In that way we have an opportunity to help the community while also setting a president for who we are... WE ARE THE BUILDERS! :)

**Comment by justinlewis** [comment]
Actionable
1. Make clear that this is for civic projects and not business building
2. Define constraints

**Comment by justinlewis** [comment]
Closing because a separate repo has been created for this event and the above tasks have been converted to tickets there. 

https://github.com/RoaringForkTech/EndOfYearCelebrationAndAppContest2018
